### ISSUE TITLE
Using which css class for validation errors?

### ISSUE THREAD

**Issue by Gentlehag** [OfficeDev/Office-UI-Fabric#208]
Hi

I've the following code in a form. What css class shoud I use for validation messages from asp-validation-for?

´´´html
     <div class="ms-Dialog-inner">
                    <div class="ms-TextField is-required">
                        <label class="ms-Label">User Name</label>
                        <input class="ms-TextField-field" type="text" asp-for="UserName">
                        <span class="ms-TextField-description">You use this to sign in.</span><br />
                        <span class="ms-TextField" asp-validation-for="UserName"></span>
                    </div>
´´´

**Comment by ericthompson** [comment]
We have some classes you can use generally to help out with alerts, errors, info, and success states:
```css
// Utility colors
.ms-fontColor-error, 
.ms-fontColor-error--hover:hover {
  color: @ms-color-error;
}

.ms-fontColor-alert, 
.ms-fontColor-alert--hover:hover {
  color: @ms-color-alert;
}

.ms-fontColor-info, 
.ms-fontColor-info--hover:hover {
  color: @ms-color-info;
}

.ms-fontColor-success, 
.ms-fontColor-success--hover:hover {
  color: @ms-color-success;
}
```
These were designed to help out with validation scenarios in mind. Does this help?
