### ISSUE TITLE
Fix ContextualMenu animations

### ISSUE THREAD

**Issue by s-KaiNet** [OfficeDev/Office-UI-Fabric#287]
ng-officeuifabric here :)  
We are implementing animation for contextual menu component. Current UI Fabric css styles make this work a little bit harder. Consider this [plunk](http://plnkr.co/edit/0mPKopikCK8RODoJ2ptH?p=preview).   
There are three menus - issue, no issue and fixed. When clicking on "issue" `Move` sub menu, fade in animation is applied correctly, but when clicking on `Delete`, during fade out there are no border (list styles are missing, etc.) on sub menu, which is not cool.   
This fixed in "no issue" menu by copying styles from UI Fabric css (consider `style.css` file and `.noissue` styles), which also is not good, cause styles may change.   

The cause of this behavior is that `.ms-ContextualMenu` (which is considered to be a "hidden" menu) and `.ms-ContextualMenu.is-open` (which is "opened" menu) have different styles. When fade out is in progress, menu has only `.ms-ContextualMenu` class styles and styles from `.ms-ContextualMenu.is-open` are missing. That's why there are no borders, etc.   
Is it better to put all required styles under  `.ms-ContextualMenu` (which is "hidden"), and "opened" menu in turns will contain only `display:block` style?  This approach demonstrated under "Fixed" menu section (file `fixed.context.menu.css`). Since `.ms-ContextualMenu` is hidden (`display:none`) it doesn't matter which styles it holds.    
From .less view it will be something like this one (`ContextualMenu.less`):   

```css
.ms-ContextualMenu {
  .ms-font-m;
  .drop-shadow;
  background-color: @ms-color-white;
  border: 1px solid @ms-color-neutralTertiaryAlt;
  list-style-type: none;
  position: absolute;
  width: 180px;
  z-index: (@ms-zIndex-ContextualMenu + @ms-zIndex-middle);
  display: none;

  // Hidden by default, then trigger this state to show it.
  &.is-open {
    display: block;
  }
}
```   
If you approve I can do a PR.
