### ISSUE TITLE
Question: Does anyone know how to disable a button in a commandbar component?

### ISSUE THREAD

**Issue by kasajian** [OfficeDev/Office-UI-Fabric#376]
Referring to commandbars: http://dev.office.com/fabric/components/commandbar
Does anyone know how to **_disable_** a commandbar component?

This is what I currently do:

1.  To make the button look disabled, I do this:
    For the anchor element with class ms-CommandBarItem-link, I add class ms-CommandBarItem-link-disabled (defined below)
    For the span element with class ms-CommandBarItem-commandText, I add class ms-CommandBarItem-commandText-disabled.

New css classes:
```css
.ms-CommandBarItem-link-disabled {
    background-color: #eff6fc;
    cursor: default;
    color:#a0a0a0 !important;
}

.ms-CommandBarItem-link-disabled:focus:before {
  border: 0 ;
}

.ms-CommandBarItem-commandText-disabled {
    color:#a0a0a0 !important;
}
```

2.  When the user clicks on the anchor (the element with class ms-CommandBarItem-link), i have an onclick() handler:
    onclick="doCommand();"
where doCommand() is some JavaScript that performs the command associated with the button.  I check for the existance of the ms-CommandBarItem-link-disabled class and if it's there, I do't invoke the command.

Is there a better way to do it?  Is it documented anywhere?
