### ISSUE TITLE
Add screen reader utility class

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/Office-UI-Fabric#439]
Something like `sr-only` class in bootstrap.

```css
.sr-only {
    position: absolute;
    width: 1px;
    height: 1px;
    padding: 0;
    margin: -1px;
    overflow: hidden;
    clip: rect(0,0,0,0);
    border: 0;
}
```
