### ISSUE TITLE
Add text align utility class

### ISSUE THREAD

**Issue by lijunle** [OfficeDev/Office-UI-Fabric#440]
Add text align utility class and override in RTL environment.

Example:

```css
.text-align-right {
    text-align: right;
}
```
